"use client";

import { useEffect, useMemo, useState } from "react";
import { SiteHeader } from "./SiteHeader";

type RankedApp = { rank: number; id: string; name: string; developer: string; iconUrl: string; price: number; genres: string[] };
const collectionLabels: Record<string,string> = { topfreeapplications: "免费榜", toppaidapplications: "付费榜", topgrossingapplications: "畅销榜" };

export function RankingsDashboard() {
  const [country,setCountry]=useState("cn"); const [collection,setCollection]=useState("topfreeapplications"); const [apps,setApps]=useState<RankedApp[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [updated,setUpdated]=useState("");
  useEffect(()=>{let active=true;setLoading(true);setError("");fetch(`/api/v1/rankings?country=${country}&collection=${collection}&limit=50`).then(r=>r.json().then(p=>({r,p}))).then(({r,p})=>{if(!r.ok)throw new Error(p.error?.message||"榜单暂时不可用");if(active){setApps(p.data);setUpdated(p.meta.fetchedAt)}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[country,collection]);
  const publisherCount=useMemo(()=>new Set(apps.map(a=>a.developer)).size,[apps]);
  return <main><SiteHeader/><section className="dashboard-shell"><div className="dashboard-title"><div><span className="kicker">APP STORE INTELLIGENCE</span><h1>数据大盘</h1><p>从榜单发现变化，再进入 App 查看评分、评论和关键词。</p></div><div className="dashboard-filter"><select value={country} onChange={e=>setCountry(e.target.value)}><option value="cn">中国</option><option value="us">美国</option><option value="jp">日本</option></select><span>iPhone</span></div></div><div className="metric-row"><div><span>当前收录</span><strong>{loading?"—":apps.length}</strong><small>榜单 App</small></div><div><span>开发者</span><strong>{loading?"—":publisherCount}</strong><small>独立发行商</small></div><div><span>数据地区</span><strong>{country.toUpperCase()}</strong><small>当前市场</small></div><div className="metric-accent"><span>数据状态</span><strong>{error?"异常":"实时"}</strong><small>{updated?new Date(updated).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"}):"正在更新"}</small></div></div><div className="rank-panel"><div className="rank-toolbar"><div className="segmented">{Object.entries(collectionLabels).map(([value,label])=><button className={collection===value?"active":""} onClick={()=>setCollection(value)} key={value}>{label}</button>)}</div><span>{country.toUpperCase()} · {collectionLabels[collection]} · Top 50</span></div>{error&&<div className="error-card">{error}</div>}<div className="rank-table"><div className="rank-head"><span>排名</span><span>App</span><span>分类</span><span>价格</span><span></span></div>{loading?Array.from({length:8}).map((_,i)=><div className="rank-row skeleton-row" key={i}/>):apps.map(app=><a className="rank-row" href={`/apps/${app.id}?country=${country}`} key={app.id}><strong className={app.rank<=3?"top-rank":""}>{app.rank}</strong><div className="rank-app"><img src={app.iconUrl} alt=""/><div><b>{app.name}</b><small>{app.developer}</small></div></div><span className="genre-pill">{app.genres[0]||"App"}</span><span>{app.price===0?"免费":app.price.toLocaleString()}</span><span className="row-arrow">→</span></a>)}</div></div></section></main>;
}
