import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", { id: integer("id").primaryKey({ autoIncrement: true }), email: text("email").notNull(), passwordHash: text("password_hash").notNull(), passwordSalt: text("password_salt").notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("idx_users_email").on(table.email)]);
export const sessions = sqliteTable("sessions", { id: integer("id").primaryKey({ autoIncrement: true }), tokenHash: text("token_hash").notNull(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), createdAt: integer("created_at", { mode: "timestamp" }).notNull(), expiresAt: integer("expires_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("idx_sessions_token_hash").on(table.tokenHash), index("idx_sessions_user_id").on(table.userId), index("idx_sessions_expires_at").on(table.expiresAt)]);

export const apps = sqliteTable("apps", { id: integer("id").primaryKey({ autoIncrement: true }), appleId: text("apple_id").notNull(), bundleId: text("bundle_id"), name: text("name").notNull(), developer: text("developer"), iconUrl: text("icon_url"), createdAt: integer("created_at", { mode: "timestamp" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("idx_apps_apple_id").on(table.appleId)]);
export const appSnapshots = sqliteTable("app_snapshots", { id: integer("id").primaryKey({ autoIncrement: true }), appId: integer("app_id").notNull().references(() => apps.id), country: text("country").notNull(), version: text("version"), price: real("price"), rating: real("rating"), ratingCount: integer("rating_count"), description: text("description"), releaseNotes: text("release_notes"), genresJson: text("genres_json"), primaryGenre: text("primary_genre"), currency: text("currency"), contentRating: text("content_rating"), minimumOsVersion: text("minimum_os_version"), fileSizeBytes: integer("file_size_bytes"), releaseDate: integer("release_date", { mode: "timestamp" }), currentVersionReleaseDate: integer("current_version_release_date", { mode: "timestamp" }), screenshotsJson: text("screenshots_json"), storeUrl: text("store_url"), rawJson: text("raw_json"), fetchedAt: integer("fetched_at", { mode: "timestamp" }).notNull() }, (table) => [index("idx_app_snapshots_app_country_time").on(table.appId, table.country, table.fetchedAt)]);
export const appCategories = sqliteTable("app_categories", { id: integer("id").primaryKey({ autoIncrement: true }), country: text("country").notNull(), categoryId: text("category_id").notNull(), name: text("name").notNull(), parentId: text("parent_id"), rawJson: text("raw_json"), fetchedAt: integer("fetched_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("idx_app_categories_country_category").on(table.country, table.categoryId), index("idx_app_categories_country_parent").on(table.country, table.parentId)]);
export const rankingSnapshots = sqliteTable("ranking_snapshots", { id: integer("id").primaryKey({ autoIncrement: true }), appId: integer("app_id").notNull().references(() => apps.id), country: text("country").notNull(), category: text("category").notNull(), collection: text("collection").notNull(), rank: integer("rank").notNull(), fetchedAt: integer("fetched_at", { mode: "timestamp" }).notNull() }, (table) => [index("idx_rankings_market_time").on(table.country, table.category, table.collection, table.fetchedAt)]);
export const reviews = sqliteTable("reviews", { id: integer("id").primaryKey({ autoIncrement: true }), providerId: text("provider_id").notNull(), appId: integer("app_id").notNull().references(() => apps.id), country: text("country").notNull(), rating: integer("rating").notNull(), title: text("title"), body: text("body").notNull(), author: text("author"), appVersion: text("app_version"), publishedAt: integer("published_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("idx_reviews_provider_country").on(table.providerId, table.country), index("idx_reviews_app_country_time").on(table.appId, table.country, table.publishedAt)]);
export const reviewSyncState = sqliteTable("review_sync_state", { appId: integer("app_id").notNull().references(() => apps.id), country: text("country").notNull(), fetchedAt: integer("fetched_at", { mode: "timestamp" }).notNull() }, (table) => [uniqueIndex("idx_review_sync_app_country").on(table.appId, table.country)]);
export const keywords = sqliteTable("keywords", { id: integer("id").primaryKey({ autoIncrement: true }), keyword: text("keyword").notNull(), country: text("country").notNull(), language: text("language").notNull() }, (table) => [uniqueIndex("idx_keywords_keyword_country").on(table.keyword, table.country)]);
export const keywordRankings = sqliteTable("keyword_ranking_snapshots", { id: integer("id").primaryKey({ autoIncrement: true }), keywordId: integer("keyword_id").notNull().references(() => keywords.id), appId: integer("app_id").notNull().references(() => apps.id), rank: integer("rank").notNull(), fetchedAt: integer("fetched_at", { mode: "timestamp" }).notNull() }, (table) => [index("idx_keyword_rankings_keyword_time").on(table.keywordId, table.fetchedAt)]);
export const insights = sqliteTable("insights", { id: integer("id").primaryKey({ autoIncrement: true }), type: text("type").notNull(), title: text("title").notNull(), conclusion: text("conclusion").notNull(), recommendation: text("recommendation"), evidenceJson: text("evidence_json").notNull(), confidence: text("confidence").notNull(), status: text("status").notNull().default("pending"), appId: integer("app_id").references(() => apps.id), keywordId: integer("keyword_id").references(() => keywords.id), generatedAt: integer("generated_at", { mode: "timestamp" }).notNull() });
